site_name: FastAgent
nav:
    - Home: index.md
    - About: about.md

repo_url: https://github.com/DETeam-GitHub/FastAgent
repo_name: FastAgent

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github

  language: zh
  logo: f.svg
  favicon: f.svg
  features: 
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 简体中文
      link: /
      lang: zh
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DETeam-Github/FastAgent_Docs
      name: FastAgent_Docs
    - icon: fontawesome/brands/github
      link: https://github.com/DETeam-Github/FastAgent
      name: FastAgent

copyright: Copyright &copy; 2023 - 2024 DebugEpoch
